// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADnZSH_RyEtVk0NNxb9tKbv0hOY4VbGYU',
    appId: '1:8892893645:web:8c149f2a4b62c300835c84',
    messagingSenderId: '8892893645',
    projectId: 'diary-app-f857e',
    authDomain: 'diary-app-f857e.firebaseapp.com',
    storageBucket: 'diary-app-f857e.firebasestorage.app',
    measurementId: 'G-TM3S9HB622',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNzG9uO-aonWd0kO-jwTIyGTWjSezh160',
    appId: '1:8892893645:android:d4efde6aa8df7a8d835c84',
    messagingSenderId: '8892893645',
    projectId: 'diary-app-f857e',
    storageBucket: 'diary-app-f857e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC77SI7cg1C_tisrRBi81EEzKWvPDJ2LlQ',
    appId: '1:8892893645:ios:b15f6813c62147b8835c84',
    messagingSenderId: '8892893645',
    projectId: 'diary-app-f857e',
    storageBucket: 'diary-app-f857e.firebasestorage.app',
    iosBundleId: 'com.example.diaryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC77SI7cg1C_tisrRBi81EEzKWvPDJ2LlQ',
    appId: '1:8892893645:ios:b15f6813c62147b8835c84',
    messagingSenderId: '8892893645',
    projectId: 'diary-app-f857e',
    storageBucket: 'diary-app-f857e.firebasestorage.app',
    iosBundleId: 'com.example.diaryApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyADnZSH_RyEtVk0NNxb9tKbv0hOY4VbGYU',
    appId: '1:8892893645:web:79de78dc95ab68ef835c84',
    messagingSenderId: '8892893645',
    projectId: 'diary-app-f857e',
    authDomain: 'diary-app-f857e.firebaseapp.com',
    storageBucket: 'diary-app-f857e.firebasestorage.app',
    measurementId: 'G-02Z4XHY3Y6',
  );
}
